# Generated by Django 3.1.7 on 2021-03-23 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('asientos', models.PositiveIntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idTour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='travels.tour')),
            ],
        ),
    ]
