# Generated by Django 3.1.7 on 2021-03-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_salida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salida',
            old_name='idTour',
            new_name='tour',
        ),
        migrations.AlterField(
            model_name='salida',
            name='asientos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
